[package]
name = "hyper-gen"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0.82"
regex = "1.9.3"

[features]
## Ada Lovelace architecture for NIVIDA RTX 4090 series
cuda-sketch-ada-lovelace = ["dep:cudarc"]

## Ampere architecture for NIVIDA A100 series
cuda-sketch-ampere = ["dep:cudarc"]

## Hopper architecture for NIVIDA H100 series
cuda-sketch-hopper = ["dep:cudarc"]

[dependencies]
log = "0.4.20"
env_logger = "0.11.3"
chrono = "0.4.38"
glob = "0.3.1"
indicatif = "0.17.7"
clap = { version = "4.4.6", features = ["cargo"] }
serde = { version = "1.0.193", features = ["derive"] }

cudarc = { version = "0.10.0", optional = true }

bincode = "1.3.3"
rayon = "1.8.0"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
indexmap = "2.0.2"

needletail = "0.5.1"
rust-seq2kminmers = "0.1.0"

ahash = "0.8.11"
wyhash = "0.5.0"
t1ha = "0.1.0"

bloom = "0.3.2"

bitpacking = "0.9.2"
ndarray = "0.15.6"

[dependencies.xxhash-rust]
version = "0.8.10"
features = ["xxh3", "const_xxh3"]

[[bin]]
name = "hyper-gen"
path = "src/main.rs"

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
opt-level = 3
panic = "abort"
lto = true
